stages:
  - test

kitchen_debian:
  stage: test
  script:
    - sleep 150
    - kitchen test debian
  tags:
    - futura

kitchen_centos:
  stage: test
  script:
    - kitchen test centos
  tags:
    - futura